//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintNow.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.PrintingCompany_Response = new HashSet<PrintingCompany_Response>();
        }
    
        public int orderID { get; set; }
        public System.DateTime orderDate { get; set; }
        public int quantity { get; set; }
        public string imagePath { get; set; }
        public string note { get; set; }
        public string printingSize { get; set; }
        public int custID { get; set; }
        public int prodID { get; set; }
        public string material { get; set; }
        public string shape { get; set; }
        public string BrowseBook { get; set; }
        public Nullable<int> NumberPages { get; set; }
        public string CollectionPapers { get; set; }
        public string Cover { get; set; }

        public HttpPostedFileBase imageFile { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrintingCompany_Response> PrintingCompany_Response { get; set; }
        public virtual Product Product { get; set; }
    }
}
