//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintingCompany_Request_Material
    {
        public int printingID { get; set; }
        public int MaterialID { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Printing_Company Printing_Company { get; set; }
    }
}
