//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printing_Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Printing_Company()
        {
            this.Product_Has_Material = new HashSet<Product_Has_Material>();
            this.PrintingCompany_Response = new HashSet<PrintingCompany_Response>();
            this.PrintingCompany_Request_Material = new HashSet<PrintingCompany_Request_Material>();
            this.Printing_Request_Shipping = new HashSet<Printing_Request_Shipping>();
        }
    
        public int printingID { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string companyName { get; set; }
        public string phone { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public byte[] image { get; set; }
        public double rate { get; set; }
        public int block { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Has_Material> Product_Has_Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrintingCompany_Response> PrintingCompany_Response { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrintingCompany_Request_Material> PrintingCompany_Request_Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Printing_Request_Shipping> Printing_Request_Shipping { get; set; }
    }
}
