//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintNow.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Supply_Material
    {
        [Required(ErrorMessage ="you have to enter the material Name")]
        [Display(Name = "Material  Name")]
        public int MaterialID { get; set; }
        public int SupplierID { get; set; }
        [Required(ErrorMessage = "you have to enter the material Price")]
        [Display(Name = "Material Price")]
        public double Price { get; set; }
        [Required(ErrorMessage = "you have to enter the material Amount")]
        [Display(Name = "Material  Amount")]
        public double amount { get; set; }
        public int ID { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
