//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintNow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printing_Request_Shipping
    {
        public int printingID { get; set; }
        public int shippingID { get; set; }
        public int amount { get; set; }
        public string shippingType { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Printing_Company Printing_Company { get; set; }
        public virtual Shipping_Company Shipping_Company { get; set; }
    }
}
