//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintNow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipping_Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipping_Company()
        {
            this.Customer_Request_Shipping = new HashSet<Customer_Request_Shipping>();
            this.Printing_Request_Shipping = new HashSet<Printing_Request_Shipping>();
        }
    
        public int shippingID { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string companyName { get; set; }
        public string phone { get; set; }
        public string city { get; set; }
        public Nullable<double> insidePricePkg { get; set; }
        public Nullable<double> outsidePricePkg { get; set; }
        public Nullable<double> extraPricePkg { get; set; }
        public Nullable<double> rate { get; set; }
        public string address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Request_Shipping> Customer_Request_Shipping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Printing_Request_Shipping> Printing_Request_Shipping { get; set; }
    }
}
