//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.PritingCompany_Response = new HashSet<PritingCompany_Response>();
        }
    
        public int orderID { get; set; }
        public System.DateTime orderDate { get; set; }
        public int quantity { get; set; }
        public byte[] image { get; set; }
        public string note { get; set; }
        public string printingSize { get; set; }
        public int custID { get; set; }
        public int prodID { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PritingCompany_Response> PritingCompany_Response { get; set; }
        public virtual Product Product { get; set; }
    }
}
