//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PritingCompany_Response
    {
        public int printingID { get; set; }
        public int orderID { get; set; }
        public double servicesPrice { get; set; }
        public double price { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Printing_Company Printing_Company { get; set; }
    }
}
